apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-send-deployment
  labels:
    app: data-send
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-send
  template:
    metadata:
      labels:
        app: data-send
    spec:
      containers:
      - name: data-send
        image: data-send:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80


