apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment-service
  labels:
    app: golang-test-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-test-service
  template:
    metadata:
      labels:
        app: golang-test-service
    spec:
      containers:
      - name: golang
        image: golang:latest
        command:
          - "sleep"
          - "604800"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: golang-deployment-service
spec:
  type: NodePort
  selector:
    app: golang-test-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30113