# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/closedlooppooc.closedloop.io_closedloops.yaml
- bases/closedlooppooc.closedloop.io_monitorings.yaml
- bases/closedlooppooc.closedloop.io_decisions.yaml
- bases/closedlooppooc.closedloop.io_executions.yaml
- bases/closedlooppooc.closedloop.io_monitoringv2s.yaml
- bases/closedlooppooc.closedloop.io_decisionv2s.yaml
- bases/closedlooppooc.closedloop.io_executionv2s.yaml
- bases/closedlooppooc.closedloop.io_closedloopds.yaml
- bases/closedlooppooc.closedloop.io_monitoringds.yaml
- bases/closedlooppooc.closedloop.io_decisionds.yaml
- bases/closedlooppooc.closedloop.io_executionds.yaml
- bases/closedlooppooc.closedloop.io_monitoringdv2s.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_closedloops.yaml
#- patches/webhook_in_monitorings.yaml
#- patches/webhook_in_decisions.yaml
#- patches/webhook_in_executions.yaml
#- patches/webhook_in_monitoringv2s.yaml
#- patches/webhook_in_decisionv2s.yaml
#- patches/webhook_in_executionv2s.yaml
#- patches/webhook_in_closedloopds.yaml
#- patches/webhook_in_monitoringds.yaml
#- patches/webhook_in_decisionds.yaml
#- patches/webhook_in_executionds.yaml
#- patches/webhook_in_monitoringdv2s.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_closedloops.yaml
#- patches/cainjection_in_monitorings.yaml
#- patches/cainjection_in_decisions.yaml
#- patches/cainjection_in_executions.yaml
#- patches/cainjection_in_monitoringv2s.yaml
#- patches/cainjection_in_decisionv2s.yaml
#- patches/cainjection_in_executionv2s.yaml
#- patches/cainjection_in_closedloopds.yaml
#- patches/cainjection_in_monitoringds.yaml
#- patches/cainjection_in_decisionds.yaml
#- patches/cainjection_in_executionds.yaml
#- patches/cainjection_in_monitoringdv2s.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
